<?php

/**
 * JSON Serialised attribute backend.  Based on the Magento Serialized backend.
 */
class Aligent_CustomFormElements_Model_Entity_Attribute_Backend_Serialized_Json
    extends Mage_Eav_Model_Entity_Attribute_Backend_Serialized {

    /**
     * Serialize before saving
     *
     * @param Varien_Object $object
     * @return Mage_Eav_Model_Entity_Attribute_Backend_Serialized
     */
    public function beforeSave($object) {
        // parent::beforeSave() is not called intentionally
        $attrCode = $this->getAttribute()->getAttributeCode();
        if ($object->hasData($attrCode)) {
            $aData = $object->getData($attrCode);

            // Remove the _empty key generated by the array UI element if it exists.
            if (is_array($aData) && array_key_exists('__empty', $aData)) {
                unset($aData['__empty']);
            }

            $object->setData($attrCode, Mage::helper('core')->jsonEncode($aData));
        }

        return $this;
    }


    /**
     * Try to unserialize the attribute value
     *
     * @param Varien_Object $object
     * @return Mage_Eav_Model_Entity_Attribute_Backend_Serialized
     */
    protected function _unserialize(Varien_Object $object) {
        $attrCode = $this->getAttribute()->getAttributeCode();
        if ($object->getData($attrCode)) {
            try {
                $unserialized = Mage::helper('core')->jsonDecode($object->getData($attrCode));
                $object->setData($attrCode, $unserialized);
            } catch (Exception $e) {
                $object->unsetData($attrCode);
            }
        }

        return $this;
    }
}
